import = ["~/.config/alacritty-theme/themes/catppuccin.toml"]

[font]
normal = {family = "MesloLGS NF", style = "Regular"}
size = 13

[window]
decorations = "none"
opacity = 0.5
startup_mode = "maximized"
