[type.os]
extend-glob = [
    "*.os.",
]
extend-ignore-re = [
    "--color",
    "\"Maximized\"",
    "_INITIALIZE",
]

[type.py]
extend-ignore-re = [
    "true_color",
]

[type.zsh]
extend-ignore-re = [
    "--color",
]
