[type.Darwin]
extend-glob = [
    "*.Darwin*",
]
extend-ignore-re = [
    "--color",
    "\"Maximized\"",
    "_INITIALIZE_",
]

[type.gitconfig]
extend-glob = [
    "*.gitconfig",
]
extend-ignore-re = [
    "colorMoved",
]

[type.Linux]
extend-glob = [
    "*.Linux",
]
extend-ignore-re = [
    "--color",
]

[type.py]
extend-ignore-re = [
    "true_color",
]

[type.vim]
extend-glob = [
    "*.vim",
]
extend-ignore-re = [
    "ColorColumn",
    "vim_markdown_math",
]

[type.zsh]
extend-ignore-re = [
    "--color",
    "_COLORS",
    "xterm-256color",
]
