[type.os]
extend-glob = [
    "*.os.*",
]
extend-ignore-re = [
    "--color",
    "\"Maximized\"",
    "_INITIALIZE_",
]

[type.py]
extend-ignore-re = [
    "true_color",
]

[type.vim]
extend-glob = [
    "*.vim",
]
extend-ignore-re = [
    "vim_markdown_math",
]

[type.zsh]
extend-ignore-re = [
    "--color",
    "xterm-256color",
]
