---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@d8081a80ce0003b82fc662944c69bb61db85e518 # v0
        with:
          licence-file: ./.github/README.md
          licence-token: ${{ secrets.LICENCE_PAT }}
