---
name: Update Copyright

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@af22ce37c920d4477d1648f4bccfaaa4e833909b # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./.github/README.md
