---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@b9cde8bcbbce838802ecd0aba2c3a7f8b82f519c # v0
        with:
          licence-file: ./.github/README.md
          licence-token: ${{ secrets.LICENCE_PAT }}
