---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@64bc0b0d7bd861f108dd563354084cbc349f3473 # v0
        env:
          LICENCE_TOKEN: ${{ secrets.LICENCE_PAT }}
        with:
          licence-file: ./.github/README.md
          licence-token: ${{ env.LICENCE_TOKEN }}
