---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@64bc0b0d7bd861f108dd563354084cbc349f3473 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
