---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@57ebd0e81973380b950e8d9083458a3c260d10ac # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
