---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@ac424c5397b4f9c7a6c082bb7196373a887e44f4 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
