name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    steps:
      - name: Install yadm (macOS)
        run: brew install yadm
        if: runner.os == 'macOS'

      - name: Install dotfiles
        run: |-
          cd ${HOME}
          yadm clone --bootstrap https://github.com/paddyroddy/dotfiles.git
          yadm bootstrap

      - name: Source zsh
        run: zsh -c "exec zsh"
