name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get install zsh
        if: runner.os == 'Linux'

      - name: Install yadm (Linux)
        run: sudo apt-get install yadm
        if: runner.os == 'Linux'

      - name: Install yadm (macOS)
        run: brew install yadm
        if: runner.os == 'macOS'

      - name: Install dotfiles
        run: |-
          cd ${HOME}
          yadm clone https://github.com/paddyroddy/dotfiles.git

      - name: Source zsh
        run: |-
          set -e
          exec zsh
        shell: zsh {0}

